apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: emergy/hipster-frontend
    name: frontend
    resources: {}
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "localhost:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "localhost:7000"
      - name: CART_SERVICE_ADDR
        value: "localhost:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "localhost:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "localhost:50051"
      - name: CHECKOUT_SERVICE_ADDR
        value: "localhost:5050"
      - name: AD_SERVICE_ADDR
        value: "localhost:9555"
      - name: ENV_PLATFORM
        value: "test"

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
